### ISSUE TITLE
Mudlark 0.2.0: AttributeError: 'float' object has no attribute 'lower'

### ISSUE THREAD

**Issue by chayG5** [nlp-tlp/mudlark#13]
Hi @Michael-Stewart-Webdev, 

I'm currently facing an issue while pre-processing a large file of work orders (~18000 rows) using Mudlark 0.2.0. When attempting to process the entire dataset, I encounter the following error:
```
AttributeError: 'float' object has no attribute 'lower'
```
Mudlark 0.2.0 seems to work fine with the first few thousand rows, but breaks when processing the entire dataset. 

As a workaround, I am using version 0.1.8 which processes the file without any issues. 

I've also tried the other versions of Mudlark:
- Versions 0.1.15 - 0.1.17 same error as version 0.2.0
- Versions 0.1.9 - 0.1.14 work without errors, but the output file generated is different compared to 0.1.8

For more context and information,  I've attached a document containing the outputs for the different versions of Mudlark during testing:
[mudlark_testing.docx](https://github.com/nlp-tlp/mudlark/files/14717174/mudlark_testing.docx)

@mhodki @LisonLau @JadeynFeng - to keep track of the issue

**Comment by Michael-Stewart-Webdev** [comment]
Thanks @chayG5 . I've had a look into it and I think I've fixed it. Hopefully if you install Mudlark 0.2.1 it should work.

The 'float' object has no attribute 'lower' was an edge case that appeared when the text column had a blank value in it - for some reason Pandas was interpreting it as a number (NaN specifically) rather than text, and when that was fed through the `_correct_typos` function it died. I've fixed it by forcing the text column to be interpreted as a string.

Note also that the reason you're seeing the JSON output format is because I changed it to be the default format a while ago (I forget which version, probably 0.1.9). Now you need to specify `output_format="csv"` when calling `normalise_csv`. You also don't need the `quickgraph_output_columns` unless using the QuickGraph format (which is the default, JSON, one).

Also noting that you've probably already noticed this but the second argument is now the text column, rather than the output filename (as I wanted it to be possible to run this programatically in Python without needing to output to a file).

So for your purposes the code for running Mudlark would be:

```
from mudlark import normalise_csv

normalise_csv(
    "../sensitive_data/wo_pumps2.csv",
    "Order Short Text",
    output_path="../sensitive_data/test_output.csv",
    drop_duplicates=True,
    output_format="csv",
)
```
